x = "Hello World"
x = 50
x = 60.5
x = 3j
x = ["geeks", "for", "geeks"]
x = ("geeks", "for", "geeks")
x = {"name": "Suraj", "age": 24}
x = {"geeks", "for", "geeks"}
x = True # bool 
x = b"Geeks" # binary
